package report

import (
	"regexp"
	"strings"
	"testing"
)

// inline() leaves no GitHub-flavored extended autolink (URL, www. or e-mail
// address) or mention in text that candidate code can write, and it removes
// every bidirectional formatting character the exports remove.
func TestInlineBreaksAutolinksAndBidi(t *testing.T) {
	in := "see https://evil.example/x, HTTP://evil.example, WWW.evil.example, ftp://h and mail me@evil.example or @octocat " +
		"\u202a\u202b\u202c\u202d\u202e\u2066\u2067\u2068\u2069\u200e\u200f\u061c end"
	got := inline(in)
	for _, bad := range []string{"://", "www.", "WWW."} {
		if strings.Contains(got, bad) {
			t.Errorf("inline kept %q: %q", bad, got)
		}
	}
	if regexp.MustCompile(`@[A-Za-z0-9]`).MatchString(got) {
		t.Errorf("inline kept an e-mail address or mention: %q", got)
	}
	for _, r := range got {
		if isBidi(r) {
			t.Errorf("inline kept the bidirectional character %U: %q", r, got)
		}
	}
	// The visible text is unchanged apart from the zero-width spaces and the
	// bidi characters turned into spaces.
	visible := strings.ReplaceAll(got, zeroWidthSpace, "")
	if !strings.Contains(visible, "see https://evil.example/x, HTTP://evil.example, WWW.evil.example, ftp://h and mail me@evil.example or @octocat") {
		t.Errorf("visible text changed: %q", visible)
	}
	if want := "Generated by Probe v1\\_x@" + zeroWidthSpace + "y (https://github.com/gvinsot/Probe)."; Attribution("v1_x@y") != want {
		t.Errorf("attribution %q, want %q", Attribution("v1_x@y"), want)
	}
}
