package report

// PR-comment export (PR_COMMENT.md), GitHub-flavored Markdown.
//
// The body sits between model.PRCommentBegin and model.PRCommentEnd, so that a
// pull-request description that quotes it is stripped from the intent. It
// opens with a status block that is not a finding (exit code, unverified
// areas, checks that did not pass, stages that did not run, and the fixed
// sentence "No finding is not approval."), then lists the evidence-backed
// findings by class. Every repository, model or report string goes through
// commentText, which breaks mentions, "#1" and "GH-1" issue references, emoji
// shortcodes and URL autolinks; the only link is the validated --report-url,
// besides the constant attribution notice. Bare commit SHAs and autolinks a
// repository configures for itself are not neutralized. The comment never
// reads as an approval.

import (
	"bytes"
	"fmt"
	"regexp"
	"strings"

	"github.com/gvinsot/Probe/app/internal/model"
)

const (
	maxCommentBytes    = 60000
	maxCommentFindings = 50
	// commentCutReserve keeps room for the sentence that replaces the findings
	// a cut leaves out.
	commentCutReserve = 512
	maxListedChecks   = 10
)

var (
	colonWord  = regexp.MustCompile(`:([A-Za-z0-9_+-])`)
	hashNumber = regexp.MustCompile(`#([0-9])`)
	ghNumber   = regexp.MustCompile(`(?i)(gh-)([0-9])`)
	// commentMarkdown is the escaping of inline() (report.go) with one
	// difference: of the HTML characters it escapes only "&", "<" and ">".
	// inline() also turns quotes into the numeric entities "&#39;" and
	// "&#34;", which in a comment would show as those entities and put a "#"
	// before a digit back into the text. A quote starts nothing once "<" is
	// escaped and the brackets and parentheses of a link are backslash-escaped.
	commentMarkdown = strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;",
		"\\", "\\\\", "`", "\\`", "*", "\\*", "_", "\\_", "[", "\\[", "]", "\\]", "(", "\\(", ")", "\\)", "#", "\\#", "|", "\\|", "!", "\\!")
)

// commentText renders an untrusted string for the PR comment. It cuts the
// string to limit bytes (UTF-8 safe, with an ellipsis), replaces control and
// bidirectional characters, breaks "@" mentions, "://" and "www." autolinks,
// ":name" shortcodes, "#1" and "GH-1" issue references with a zero-width
// space, then escapes "&", "<" and ">" as HTML and backslash-escapes the
// Markdown punctuation that inline() escapes. The output never has a "#"
// directly before a digit.
func commentText(s string, limit int) string {
	s = bounded(s, limit)
	s = strings.ReplaceAll(s, "@", "@"+zeroWidthSpace)
	s = breakLinks(s)
	s = colonWord.ReplaceAllString(s, ":"+zeroWidthSpace+"$1")
	s = hashNumber.ReplaceAllString(s, "#"+zeroWidthSpace+"$1")
	s = ghNumber.ReplaceAllString(s, "${1}"+zeroWidthSpace+"${2}")
	s = commentMarkdown.Replace(s)
	// The escaping adds no "#"; applying the rule to the output keeps it true
	// whatever the escaping does.
	return hashNumber.ReplaceAllString(s, "#"+zeroWidthSpace+"$1")
}

// prAttribution is Attribution with the version rendered through commentText,
// so a version string read from a re-rendered report cannot mention anyone.
// For an ordinary version it equals Attribution(version).
func prAttribution(version string) string {
	if version == "" {
		return Attribution(version)
	}
	return fmt.Sprintf("Generated by Probe %s (%s).", commentText(version, 128), probeURI)
}

func plural(n int, one, many string) string {
	if n == 1 {
		return fmt.Sprintf("%d %s", n, one)
	}
	return fmt.Sprintf("%d %s", n, many)
}

// renderPRComment renders the PR comment of a sanitized, finalized report.
func renderPRComment(r *model.Report, set findingSet, reportURL string) []byte {
	status := statusOf(r)
	var b bytes.Buffer
	line(&b, model.PRCommentBegin)
	total := len(set.findings) + set.omitted
	switch total {
	case 0:
		line(&b, "## Probe: no evidence-backed finding recorded")
	case 1:
		line(&b, "## Probe: 1 evidence-backed finding")
	default:
		line(&b, fmt.Sprintf("## Probe: %d evidence-backed findings", total))
	}
	line(&b, "")
	writeCommentStatus(&b, status)
	line(&b, "")
	line(&b, evidenceOnlyText)

	tail := commentTail(r, reportURL)
	budget := maxCommentBytes - len(tail) - commentCutReserve
	shown := 0
	lastClass := ""
	counts := map[string]int{}
	for _, f := range set.findings {
		counts[f.Class]++
	}
	for _, f := range set.findings {
		var block bytes.Buffer
		if f.Class != lastClass {
			cls, _ := classByName(f.Class)
			line(&block, "")
			line(&block, fmt.Sprintf("### %s (%d)", cls.Heading, counts[f.Class]))
			line(&block, "")
			line(&block, cls.Caveat)
			line(&block, "")
		}
		writeCommentFinding(&block, f)
		if shown == maxCommentFindings || b.Len()+block.Len() > budget {
			break
		}
		b.Write(block.Bytes())
		lastClass = f.Class
		shown++
	}
	if hidden := total - shown; hidden > 0 {
		line(&b, "")
		line(&b, fmt.Sprintf("%s not shown in this comment, which lists at most %d findings in at most %d bytes; the underlying records are in confidence-report.json.",
			plural(hidden, "further evidence-backed finding is", "further evidence-backed findings are"), maxCommentFindings, maxCommentBytes))
	}
	b.WriteString(tail)
	return b.Bytes()
}

// writeCommentStatus writes the status block, which is not a finding.
func writeCommentStatus(b *bytes.Buffer, s exportStatus) {
	line(b, "**Status (not a finding)**")
	line(b, "")
	line(b, "- "+exitSentence(s.ExitCode))
	line(b, fmt.Sprintf("- Unverified areas: %d (%s and %s that stayed UNVERIFIED).", s.UnverifiedAreas(),
		plural(len(s.UnverifiedNotes), "recorded note", "recorded notes"), plural(len(s.UnverifiedHypotheses), "hypothesis", "hypotheses")))
	checks := fmt.Sprintf("- Checks that did not pass: %d (the mutation ledger is not counted)", len(s.ChecksNotPassed))
	if len(s.ChecksNotPassed) > 0 {
		var listed []string
		for i, c := range s.ChecksNotPassed {
			if i == maxListedChecks {
				listed = append(listed, fmt.Sprintf("%d more", len(s.ChecksNotPassed)-maxListedChecks))
				break
			}
			listed = append(listed, fmt.Sprintf("%s %s %s", commentText(c.ID, 64), commentText(c.Kind, 64), commentText(c.Status, 32)))
		}
		checks += ": " + strings.Join(listed, "; ")
	}
	line(b, checks+".")
	stages := fmt.Sprintf("- Stages that did not run: %d", len(s.StagesNotRun))
	if len(s.StagesNotRun) > 0 {
		var listed []string
		for _, st := range s.StagesNotRun {
			item := st.Name + " (" + commentText(st.Status, 32)
			if strings.TrimSpace(st.Reason) != "" {
				item += ": " + commentText(st.Reason, maxReasonBytes)
			}
			listed = append(listed, item+")")
		}
		stages += ": " + strings.Join(listed, "; ")
	}
	line(b, stages+".")
	if s.NoExecution {
		line(b, "- "+noExecutionText)
	}
	line(b, fmt.Sprintf("- Not findings, listed only in the full report: %s and %s.",
		plural(s.RiskSignals, "risk signal", "risk signals"), plural(s.ReviewTargets, "suggested review range", "suggested review ranges")))
	line(b, "- "+notApprovalText)
}

// writeCommentFinding writes one finding as a list item with sub-items.
func writeCommentFinding(b *bytes.Buffer, f finding) {
	var head []string
	if f.Severity != "" {
		head = append(head, fmt.Sprintf("**%s** severity, assigned by the reviewer model.", commentText(f.Severity, 16)))
	}
	if f.Statement != "" {
		head = append(head, commentText(f.Statement, maxReasonBytes))
	}
	if f.Title != "" {
		head = append(head, "Reviewer-model title: "+commentText(f.Title, maxTitleBytes)+".")
	}
	head = append(head, "Location: "+commentLocation(f)+".")
	line(b, "- "+strings.Join(head, " "))
	ids := "Evidence: " + commentIDs(f.EvidenceIDs) + ". Checks: " + commentIDs(f.CheckIDs) + "."
	if len(f.EvidenceIDs) == 0 {
		ids = "Checks: " + commentIDs(f.CheckIDs) + " (mutation ledger)."
	}
	line(b, "  - "+ids)
	if len(f.replayed) > 0 {
		line(b, "  - Checks "+commentIDs(f.replayed)+" were "+replayedChecksTxt+".")
	}
	if len(f.HypothesisIDs) > 0 {
		line(b, "  - Hypotheses: "+commentIDs(f.HypothesisIDs)+".")
	}
	for _, d := range f.Details {
		line(b, "  - "+capitalize(commentText(d.Label, maxLabelBytes))+": "+commentText(d.Value, maxValueBytes))
	}
	for _, a := range f.Artifacts {
		line(b, "  - Retained "+commentText(a.Kind, 64)+" artifact: sha256 "+commentText(a.SHA256, 64)+" ("+commentText(a.Path, maxValueBytes)+")")
	}
	if f.Class == ClassIntentTestFailed && len(f.Artifacts) == 0 {
		line(b, "  - The retained intent test could not be matched to exactly one artifact; see the Artifacts section of the full report.")
	}
	if f.truncated {
		line(b, "  - Some values were cut or omitted; the full values are in confidence-report.json.")
	}
}

func commentIDs(ids []string) string {
	if len(ids) == 0 {
		return "none"
	}
	return commentText(strings.Join(ids, ", "), maxValueBytes)
}

// commentLocation renders a finding's anchor, or says there is none.
func commentLocation(f finding) string {
	a := f.anchor
	switch {
	case a == nil:
		return "none in the changed files"
	case a.FileLevel && a.Source == locModel:
		return commentText(a.Path, maxValueBytes) + " (" + fileLevelText + ")"
	case a.FileLevel:
		return commentText(a.Path, maxValueBytes) + " (file-level; " + a.Source + ")"
	}
	location := commentText(a.Path, maxValueBytes) + fmt.Sprintf(":%d", a.Line)
	if a.EndLine > a.Line {
		location += fmt.Sprintf("–%d", a.EndLine)
	}
	return location + " (" + a.Source + ")"
}

// commentTail is the pointer to the full report, the attribution and the end
// marker; it is never cut.
func commentTail(r *model.Report, reportURL string) string {
	var b bytes.Buffer
	line(&b, "")
	if reportURL != "" && ValidateReportURL(reportURL) == nil {
		line(&b, "Full report: [CONFIDENCE\\_REPORT.md and confidence-report.json]("+reportURL+")")
	} else {
		line(&b, "Full report: CONFIDENCE\\_REPORT.md and confidence-report.json in the Probe report directory.")
	}
	line(&b, "")
	line(&b, "---")
	line(&b, "")
	line(&b, prAttribution(r.ToolVersion))
	line(&b, model.PRCommentEnd)
	return b.String()
}
