package harness

import (
	"context"
	"reflect"
	"strings"
	"testing"
	"time"

	"github.com/gvinsot/Probe/app/internal/model"
)

const pythonFuzzPath = "pkg/test_probe_fuzz_abcdef12.py"

// pythonFuzzSource stands for a rendered Python fuzz harness: the harness side
// needs only its top-level test functions.
const pythonFuzzSource = `# Code generated by Probe differential fuzzing (probe-fuzz/v1). DO NOT EDIT.


def test_probe_fuzz_abcdef12_1():
    pass


def test_probe_fuzz_abcdef12_2():
    pass
`

var pythonFuzzNames = []string{"test_probe_fuzz_abcdef12_1", "test_probe_fuzz_abcdef12_2"}

func pythonFuzzRun() ObservedRun {
	return ObservedRun{Path: pythonFuzzPath, Content: pythonFuzzSource, TestNames: pythonFuzzNames, SaveSource: true,
		Deadline: time.Now().Add(time.Minute), Normalize: testNormalize, Runner: RunnerPytest, Started: testStarted}
}

// A Python run executes the reviewed pytest template with the harness as its
// {file} target, captures only the observation stream, and records the
// runner pytest_junit.
func TestRunObservedPythonCommandAndRunner(t *testing.T) {
	h := fixture(t)
	h.opts.Commands["generated_test"] = append([]string(nil), pytestTemplate...)
	argvs := fakeFuzz(t, h,
		fuzzSideRun{log: "pytest log", payload: coverageFrame("stream:started:started:")},
		fuzzSideRun{log: "pytest log", payload: coverageFrame("stream:started:started:")})
	base, candidate, err := h.RunObserved(context.Background(), pythonFuzzRun())
	if err != nil {
		t.Fatal(err)
	}
	command := []string{"python3", "-m", "pytest", "-p", "no:cacheprovider", pythonFuzzPath, "--junitxml=" + ResultsPath}
	if !reflect.DeepEqual(base.Check.Command, command) || !reflect.DeepEqual(candidate.Check.Command, command) {
		t.Fatalf("commands %q %q", base.Check.Command, candidate.Check.Command)
	}
	for _, args := range *argvs {
		if !strings.Contains(strings.Join(args, " "), FuzzObservationsPath) {
			t.Fatalf("argv %q", args)
		}
	}
	if base.Check.Status != "PASS" || candidate.Check.Status != "PASS" || h.fuzz.runners[base.Check.ID] != RunnerPytest {
		t.Fatalf("checks %+v %+v runners %v", base.Check, candidate.Check, h.fuzz.runners)
	}
	e, err := h.AddFuzzEvidence(model.Evidence{Kind: model.EvidenceDifferentialFuzz, Status: model.StatusNotDiverged, Runner: RunnerPytest,
		TestNames: []string{pythonFuzzNames[0]}, Path: pythonFuzzPath, CheckID: candidate.Check.ID, BaseCheckID: base.Check.ID})
	if err != nil || e.Runner != RunnerPytest {
		t.Fatalf("evidence %+v %v", e, err)
	}
	if _, err := h.AddFuzzEvidence(model.Evidence{Kind: model.EvidenceDifferentialFuzz, Status: model.StatusNotDiverged, Runner: RunnerJest,
		TestNames: []string{pythonFuzzNames[0]}, Path: pythonFuzzPath, CheckID: candidate.Check.ID, BaseCheckID: base.Check.ID}); err == nil {
		t.Fatal("evidence naming another runner than its checks was accepted")
	}
}

// A baseline run that returned no payload did not start the harness: the
// module or the harness could not be imported.
func TestRunObservedPythonBaselineNotStarted(t *testing.T) {
	h := fixture(t)
	h.opts.Commands["generated_test"] = append([]string(nil), pytestTemplate...)
	fakeFuzz(t, h, fuzzSideRun{log: "ImportError", exit: 2}, fuzzSideRun{log: "pytest log", payload: coverageFrame("stream:started:started:")})
	base, _, err := h.RunObserved(context.Background(), pythonFuzzRun())
	if err != nil || base.Check.Status != "ERROR" || !strings.Contains(base.Check.Output, fuzzScriptNotStarted) {
		t.Fatalf("base %+v %v", base.Check, err)
	}
}

func TestRunObservedPythonPrecheck(t *testing.T) {
	for name, tc := range map[string]struct {
		template []string
		mutate   func(*ObservedRun)
	}{
		"vitest template":     {scriptVitestTemplate, func(*ObservedRun) {}},
		"unverifiable pytest": {[]string{"pytest", "{file}"}, func(*ObservedRun) {}},
		"not a test module":   {pytestTemplate, func(r *ObservedRun) { r.Path = "pkg/probe_fuzz_abcdef12.py" }},
		"other test names":    {pytestTemplate, func(r *ObservedRun) { r.TestNames = []string{"test_probe_fuzz_abcdef12_1"} }},
		"no counter":          {pytestTemplate, func(r *ObservedRun) { r.Started = nil }},
	} {
		h := fixture(t)
		h.opts.Commands["generated_test"] = append([]string(nil), tc.template...)
		run := pythonFuzzRun()
		tc.mutate(&run)
		if _, _, err := h.RunObserved(context.Background(), run); err == nil {
			t.Errorf("%s: accepted", name)
		}
	}
}
