package cli

import (
	"bytes"
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/gvinsot/SwiftProof/app/internal/report"
)

func TestReportOptions(t *testing.T) {
	cases := []struct {
		name    string
		formats []string
		url     string
		options int
		err     string
	}{
		{"no URL", []string{"markdown", "json"}, "", 0, ""},
		{"no URL with pr-comment", []string{"pr-comment"}, "", 0, ""},
		{"URL with pr-comment", []string{"sarif", "pr-comment"}, "https://example.invalid/runs/1", 1, ""},
		{"URL without pr-comment", []string{"markdown", "json", "sarif"}, "https://example.invalid/runs/1", 0, "--report-url requires --format pr-comment"},
		{"http URL", []string{"pr-comment"}, "http://example.invalid", 0, "--report-url: the report URL must start with https://"},
		{"markdown breakout", []string{"pr-comment"}, "https://example.invalid/x)[y](https://evil.test", 0, "--report-url:"},
		{"userinfo", []string{"pr-comment"}, "https://user@example.invalid", 0, "--report-url:"},
		{"no host", []string{"pr-comment"}, "https:///runs/1", 0, "--report-url: the report URL must name a host"},
		{"too long", []string{"pr-comment"}, "https://example.invalid/" + strings.Repeat("a", 490), 0, "exceeds 512 bytes"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			opts, err := reportOptions(tc.formats, tc.url)
			if tc.err != "" {
				if err == nil || !strings.Contains(err.Error(), tc.err) {
					t.Fatalf("error %v, want %q", err, tc.err)
				}
				return
			}
			if err != nil || len(opts) != tc.options {
				t.Fatalf("%d options, error %v", len(opts), err)
			}
		})
	}
}

// lint writes the exports without executing anything; they say that nothing
// ran, and a re-render reproduces them byte for byte.
func TestLintExportsAndRerender(t *testing.T) {
	dir := fixture(t)
	var out, errOut bytes.Buffer
	code := Run(context.Background(), []string{"lint", "--repo", dir, "--base", "main", "--out", "exports", "--format", "sarif,pr-comment"}, &out, &errOut, "test")
	if code != 0 {
		t.Fatalf("exit %d: %s", code, errOut.String())
	}
	for name, want := range map[string]bool{"confidence-report.sarif": true, "PR_COMMENT.md": true, "CONFIDENCE_REPORT.md": false, "confidence-report.json": false} {
		if _, err := os.Stat(filepath.Join(dir, "exports", name)); (err == nil) != want {
			t.Errorf("%s: present %v, want %v", name, err == nil, want)
		}
	}
	sarif := readFile(t, filepath.Join(dir, "exports", "confidence-report.sarif"))
	var log struct {
		Runs []struct {
			Results     []any `json:"results"`
			Invocations []struct {
				ExecutionSuccessful bool `json:"executionSuccessful"`
				Notifications       []struct {
					Message struct {
						Text string `json:"text"`
					} `json:"message"`
				} `json:"toolExecutionNotifications"`
			} `json:"invocations"`
		} `json:"runs"`
	}
	if err := json.Unmarshal([]byte(sarif), &log); err != nil {
		t.Fatal(err)
	}
	if len(log.Runs) != 1 || log.Runs[0].Results == nil || len(log.Runs[0].Results) != 0 || !log.Runs[0].Invocations[0].ExecutionSuccessful {
		t.Fatalf("lint SARIF: %s", sarif)
	}
	if !strings.Contains(sarif, "No checks or experiments ran, so the absence of findings carries no information.") {
		t.Fatalf("no-execution notification missing: %s", sarif)
	}
	comment := readFile(t, filepath.Join(dir, "exports", "PR_COMMENT.md"))
	for _, want := range []string{"## SwiftProof: no evidence-backed finding recorded", "carries no information", "No finding is not approval.", "Generated by SwiftProof test (https://github.com/gvinsot/SwiftProof)."} {
		if !strings.Contains(comment, want) {
			t.Errorf("PR comment lacks %q:\n%s", want, comment)
		}
	}

	// All four formats with a report URL, then two re-renders.
	url := "https://example.invalid/runs/1"
	code = Run(context.Background(), []string{"lint", "--repo", dir, "--base", "main", "--out", "full", "--format", "markdown,json,sarif,pr-comment", "--report-url", url}, &out, &errOut, "test")
	if code != 0 {
		t.Fatalf("exit %d: %s", code, errOut.String())
	}
	input := filepath.Join(dir, "full", "confidence-report.json")
	for _, target := range []string{"first", "second"} {
		code = Run(context.Background(), []string{"report", "--input", input, "--out", filepath.Join(dir, target), "--format", "sarif,pr-comment", "--report-url", url}, &out, &errOut, "test")
		if code != 0 {
			t.Fatalf("report exit %d: %s", code, errOut.String())
		}
	}
	for _, name := range []string{"confidence-report.sarif", "PR_COMMENT.md"} {
		original := readFile(t, filepath.Join(dir, "full", name))
		if a, b := readFile(t, filepath.Join(dir, "first", name)), readFile(t, filepath.Join(dir, "second", name)); a != b || a != original {
			t.Fatalf("%s is not reproduced by a re-render", name)
		}
	}
	if !strings.Contains(readFile(t, filepath.Join(dir, "full", "PR_COMMENT.md")), "[CONFIDENCE\\_REPORT.md and confidence-report.json]("+url+")") {
		t.Fatal("report URL not linked")
	}
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(b)
}

// Export flag errors exit 3 before any report directory is written or any
// container starts; the render command validates before reading its input.
func TestExportFlagErrors(t *testing.T) {
	dir := fixture(t)
	for _, args := range [][]string{
		{"lint", "--format", "sarif,bogus"},
		{"review", "--format", "json,SARIF"},
		{"review", "--format", "pr-comment", "--report-url", "http://example.invalid"},
		{"review", "--format", "pr-comment", "--report-url", "https://example.invalid/(x)"},
		{"lint", "--format", "sarif", "--report-url", "https://example.invalid/runs/1"},
		{"lint", "--format", "pr-comment", "--report-url", "https://user:pw@example.invalid"},
	} {
		t.Run(strings.Join(args, " "), func(t *testing.T) {
			forbidExecution(t)
			out := filepath.Join(t.TempDir(), "report")
			var stdout, stderr bytes.Buffer
			if code := Run(context.Background(), append(append([]string{}, args...), "--repo", dir, "--out", out), &stdout, &stderr, "test"); code != 3 {
				t.Fatalf("exit %d, want 3: %s", code, stderr.String())
			}
			if _, err := os.Stat(out); !os.IsNotExist(err) {
				t.Fatalf("an exit-3 path wrote the report directory: %v", err)
			}
		})
	}
	var buf bytes.Buffer
	if code := Run(context.Background(), []string{"report", "--input", "missing.json", "--format", "pr-comment", "--report-url", "javascript:alert(1)"}, &buf, &buf, "test"); code != 3 || strings.Contains(buf.String(), "missing.json") {
		t.Fatalf("render: exit %d: %s", code, buf.String())
	}
	if !report.ValidFormat("pr-comment") || !report.ValidFormat("sarif") {
		t.Fatal("export formats not registered")
	}
}
